name: Malformation
description: Report a malformed filter rule.
title: "💔 [Malformed]: "
labels:
  - malformed
  - pending-approval
assignees:
  - igorskyflyer
body:
  - type: checkboxes
    id: initial-checks
    attributes:
      label: Initial checks
      description: All boxes must be checked. Issues that do not comply may be closed or ignored.
      options:
        - label: I have searched for [existing issues](https://github.com/the-advoid/ad-void/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) and confirmed this is not a duplicate.
          required: true

  - type: textarea
    id: rule
    attributes:
      label: Rule
      description: Paste a permalink to the rule (File → Copy permalink), or the rule itself. One rule per issue.
    validations:
      required: true
