name: Optimization
description: Suggest an optimization that makes AdVoid more efficient or compact.
title: "🚀 [Optimization]: "
labels:
  - optimization
  - pending-approval
assignees:
  - igorskyflyer
body:
  - type: checkboxes
    id: initial-checks
    attributes:
      label: Initial checks
      description: All boxes must be checked. Issues that do not comply may be closed or ignored.
      options:
        - label: I have searched for [existing issues](https://github.com/the-advoid/ad-void/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen) and confirmed this is not a duplicate.
          required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: The optimization to implement.
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation
      description: Details of the optimization implementation.
    validations:
      required: false
